language: ruby
rvm:
  - 2.2.1
cache: bundler
script:
  - /bin/bash travisSetup.sh
  - bundle exec rake
 # - bundle exec rake db:migrate VERSION=0
 # - bundle exec rake db:migrate
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

